# Generated by Django 2.1.7 on 2019-03-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=240)),
                ('album_name', models.CharField(max_length=240)),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albumy',
            },
        ),
    ]
