# Generated by Django 2.1.7 on 2019-05-08 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumy', '0003_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Posty',
            },
        ),
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
